### ISSUE TITLE
QR code error 

### ISSUE THREAD

**Issue by Ibraheem7860** [ahadnawaz585/AI-Bot-WhatsApp-Integration-REST-API#1]
When i was trying to scan QR code it shows me an error and stops working.
This is the error 
"server\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:221 [1] throw new Error('Evaluation failed: ' + helper_js_1.helper.getExceptionMessage(exceptionDetails)); [1] ^ [1] [1] Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'default') [1] at __puppeteer_evaluation_script__:5:95"
Please resolve it @ahadnawaz585

**Comment by ahadnawaz585** [comment]
> When i was trying to scan QR code it shows me an error and stops working. This is the error "server\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:221 [1] throw new Error('Evaluation failed: ' + helper_js_1.helper.getExceptionMessage(exceptionDetails)); [1] ^ [1] [1] Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'default') [1] at **puppeteer_evaluation_script**:5:95" Please resolve it @ahadnawaz585


Hi @Ibraheem0156 ,

I have resolved the issue in the latest commit.

To ensure everything works correctly, please run the following command:

```
npm install github:pedroslopez/whatsapp-web.js#webpack-exodus
```

Additionally, I have updated the `wwebVersion` to `2.2409.0`. This version is provided by the WhatsApp Web JS creator from a different branch. Although I'm not certain about its stability or if it includes all features, it works fine for my use case, even without providing a `webVersionCache` for the bot client.

The bot is functioning correctly now.

![image](https://github.com/user-attachments/assets/cdd74778-624d-40ab-b083-932c46866db9)
